language: go

go:
  - tip

install:
  - go get -u github.com/golang/lint/golint
  - go get ./...
  - go install ./...

before_script:
  - for package in $(go list ./... | grep -v '/vendor/'); do golint -set_exit_status $package; done
  - go vet $(go list ./... | grep -v '/vendor/')

script:
  - go test $(go list ./... | grep -v '/vendor/')
